### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by dep** [eugeneyan/obsidian-copilot#5]
During `make build-artifacts` I got this error:

```
Downloading pytorch_model.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 134M/134M [00:04<00:00, 31.6MB/s]
2023-06-14 16:59:43,807 - src.logger - INFO - Embedding index length: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/obsidian-copilot/src/prep/build_semantic_index.py", line 146, in <module>
    doc_embeddings_array = build_embedding_array(vault, tokenizer, model)
  File "/obsidian-copilot/src/prep/build_semantic_index.py", line 113, in build_embedding_array
    doc_embeddings_array = np.concatenate(embedding_list, axis=0)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
make: *** [build-artifacts] Error 1
```

**Comment by dep** [comment]
Seems it's because I have spaces in my Vault path.  using \ to escape them doesn't seem to help.

doesn't work:
```
export OBSIDIAN_PATH ?= /Users/dpeck/dannypeck@gmail.com\ -\ Google\ Drive/My\ Drive/Obsidian/Brain\ 2.0
```

works:
```
/Users/dpeck/tmp/obsidian
```
